FROM maven:3.9.8-eclipse-temurin-17

USER root
RUN mkdir /app
WORKDIR /app

COPY pom.xml ./
COPY src ./src

ENV ALLURE_RESULTS=/app/allure-results

ENTRYPOINT ["sh", "-c", "\
  mvn clean test \
  -Dbase_url=${BASE_URL} \
  -DdeviceName=${DEVICE_NAME} \
  -DappPackage=${APP_PACKAGE} \
  -DappActivity=${APP_ACTIVITY} \
  -DnoReset=${NO_RESET} \
  -DappUrl=${APP_URL} \
  -Dallure.results.directory=${ALLURE_RESULTS}"]